### YamlMime:ManagedReference
items:
- uid: Inetlab.SMPP.Common.MessageComposer
  commentId: T:Inetlab.SMPP.Common.MessageComposer
  id: MessageComposer
  parent: Inetlab.SMPP.Common
  children:
  - Inetlab.SMPP.Common.MessageComposer.#ctor
  - Inetlab.SMPP.Common.MessageComposer.AddMessage``1(``0)
  - Inetlab.SMPP.Common.MessageComposer.evFullMessageReceived
  - Inetlab.SMPP.Common.MessageComposer.evFullMessageTimedout
  - Inetlab.SMPP.Common.MessageComposer.GetFullMessage``1(``0)
  - Inetlab.SMPP.Common.MessageComposer.IsLastSegment``1(``0)
  - Inetlab.SMPP.Common.MessageComposer.Timeout
  langs:
  - csharp
  - vb
  name: MessageComposer
  nameWithType: MessageComposer
  fullName: Inetlab.SMPP.Common.MessageComposer
  type: Class
  source:
    remote:
      path: Source/CS/Common/MessageComposer.cs
      branch: master
      repo: C:/Users/Aleksey/Dropbox/Repos/Inetlab.SMPP.git
    id: MessageComposer
    path: ../Source/CS/Common/MessageComposer.cs
    startLine: 12
  assemblies:
  - Inetlab.SMPP
  namespace: Inetlab.SMPP.Common
  summary: "\nHelps to assemble concatenated messages\n"
  example: []
  syntax:
    content: public class MessageComposer
    content.vb: Public Class MessageComposer
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Inetlab.SMPP.Common.MessageComposer.Timeout
  commentId: P:Inetlab.SMPP.Common.MessageComposer.Timeout
  id: Timeout
  parent: Inetlab.SMPP.Common.MessageComposer
  langs:
  - csharp
  - vb
  name: Timeout
  nameWithType: MessageComposer.Timeout
  fullName: Inetlab.SMPP.Common.MessageComposer.Timeout
  type: Property
  source:
    remote:
      path: Source/CS/Common/MessageComposer.cs
      branch: master
      repo: C:/Users/Aleksey/Dropbox/Repos/Inetlab.SMPP.git
    id: Timeout
    path: ../Source/CS/Common/MessageComposer.cs
    startLine: 20
  assemblies:
  - Inetlab.SMPP
  namespace: Inetlab.SMPP.Common
  summary: "\nGets or sets time in miliseconds for waiting of all message segments.\n"
  example: []
  syntax:
    content: public int Timeout { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Timeout As Integer
  overload: Inetlab.SMPP.Common.MessageComposer.Timeout*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Inetlab.SMPP.Common.MessageComposer.evFullMessageReceived
  commentId: E:Inetlab.SMPP.Common.MessageComposer.evFullMessageReceived
  id: evFullMessageReceived
  parent: Inetlab.SMPP.Common.MessageComposer
  langs:
  - csharp
  - vb
  name: evFullMessageReceived
  nameWithType: MessageComposer.evFullMessageReceived
  fullName: Inetlab.SMPP.Common.MessageComposer.evFullMessageReceived
  type: Event
  source:
    remote:
      path: Source/CS/Common/MessageComposer.cs
      branch: master
      repo: C:/Users/Aleksey/Dropbox/Repos/Inetlab.SMPP.git
    id: evFullMessageReceived
    path: ../Source/CS/Common/MessageComposer.cs
    startLine: 25
  assemblies:
  - Inetlab.SMPP
  namespace: Inetlab.SMPP.Common
  summary: "\nOccurs when all message segments received. Contains concatenated message text.\n"
  example: []
  syntax:
    content: public event MessageEventHandler evFullMessageReceived
    return:
      type: Inetlab.SMPP.Common.MessageEventHandler
    content.vb: Public Event evFullMessageReceived As MessageEventHandler
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Inetlab.SMPP.Common.MessageComposer.evFullMessageTimedout
  commentId: E:Inetlab.SMPP.Common.MessageComposer.evFullMessageTimedout
  id: evFullMessageTimedout
  parent: Inetlab.SMPP.Common.MessageComposer
  langs:
  - csharp
  - vb
  name: evFullMessageTimedout
  nameWithType: MessageComposer.evFullMessageTimedout
  fullName: Inetlab.SMPP.Common.MessageComposer.evFullMessageTimedout
  type: Event
  source:
    remote:
      path: Source/CS/Common/MessageComposer.cs
      branch: master
      repo: C:/Users/Aleksey/Dropbox/Repos/Inetlab.SMPP.git
    id: evFullMessageTimedout
    path: ../Source/CS/Common/MessageComposer.cs
    startLine: 30
  assemblies:
  - Inetlab.SMPP
  namespace: Inetlab.SMPP.Common
  summary: "\nOccurs when all message segments were not received during <xref href=\"Inetlab.SMPP.Common.MessageComposer.Timeout\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public event MessageEventHandler evFullMessageTimedout
    return:
      type: Inetlab.SMPP.Common.MessageEventHandler
    content.vb: Public Event evFullMessageTimedout As MessageEventHandler
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Inetlab.SMPP.Common.MessageComposer.#ctor
  commentId: M:Inetlab.SMPP.Common.MessageComposer.#ctor
  id: '#ctor'
  parent: Inetlab.SMPP.Common.MessageComposer
  langs:
  - csharp
  - vb
  name: MessageComposer()
  nameWithType: MessageComposer.MessageComposer()
  fullName: Inetlab.SMPP.Common.MessageComposer.MessageComposer()
  type: Constructor
  source:
    remote:
      path: Source/CS/Common/MessageComposer.cs
      branch: master
      repo: C:/Users/Aleksey/Dropbox/Repos/Inetlab.SMPP.git
    id: .ctor
    path: ../Source/CS/Common/MessageComposer.cs
    startLine: 32
  assemblies:
  - Inetlab.SMPP
  namespace: Inetlab.SMPP.Common
  syntax:
    content: public MessageComposer()
    content.vb: Public Sub New
  overload: Inetlab.SMPP.Common.MessageComposer.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Inetlab.SMPP.Common.MessageComposer.AddMessage``1(``0)
  commentId: M:Inetlab.SMPP.Common.MessageComposer.AddMessage``1(``0)
  id: AddMessage``1(``0)
  parent: Inetlab.SMPP.Common.MessageComposer
  langs:
  - csharp
  - vb
  name: AddMessage<T>(T)
  nameWithType: MessageComposer.AddMessage<T>(T)
  fullName: Inetlab.SMPP.Common.MessageComposer.AddMessage<T>(T)
  type: Method
  source:
    remote:
      path: Source/CS/Common/MessageComposer.cs
      branch: master
      repo: C:/Users/Aleksey/Dropbox/Repos/Inetlab.SMPP.git
    id: AddMessage
    path: ../Source/CS/Common/MessageComposer.cs
    startLine: 38
  assemblies:
  - Inetlab.SMPP
  namespace: Inetlab.SMPP.Common
  syntax:
    content: 'public void AddMessage<T>(T message)where T : ISmppMessage'
    parameters:
    - id: message
      type: '{T}'
    typeParameters:
    - id: T
    content.vb: Public Sub AddMessage(Of T As ISmppMessage)(message As T)
  overload: Inetlab.SMPP.Common.MessageComposer.AddMessage*
  nameWithType.vb: MessageComposer.AddMessage(Of T)(T)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Inetlab.SMPP.Common.MessageComposer.AddMessage(Of T)(T)
  name.vb: AddMessage(Of T)(T)
- uid: Inetlab.SMPP.Common.MessageComposer.IsLastSegment``1(``0)
  commentId: M:Inetlab.SMPP.Common.MessageComposer.IsLastSegment``1(``0)
  id: IsLastSegment``1(``0)
  parent: Inetlab.SMPP.Common.MessageComposer
  langs:
  - csharp
  - vb
  name: IsLastSegment<T>(T)
  nameWithType: MessageComposer.IsLastSegment<T>(T)
  fullName: Inetlab.SMPP.Common.MessageComposer.IsLastSegment<T>(T)
  type: Method
  source:
    remote:
      path: Source/CS/Common/MessageComposer.cs
      branch: master
      repo: C:/Users/Aleksey/Dropbox/Repos/Inetlab.SMPP.git
    id: IsLastSegment
    path: ../Source/CS/Common/MessageComposer.cs
    startLine: 175
  assemblies:
  - Inetlab.SMPP
  namespace: Inetlab.SMPP.Common
  syntax:
    content: 'public bool IsLastSegment<T>(T message)where T : ISmppMessage'
    parameters:
    - id: message
      type: '{T}'
    typeParameters:
    - id: T
    return:
      type: System.Boolean
    content.vb: Public Function IsLastSegment(Of T As ISmppMessage)(message As T) As Boolean
  overload: Inetlab.SMPP.Common.MessageComposer.IsLastSegment*
  nameWithType.vb: MessageComposer.IsLastSegment(Of T)(T)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Inetlab.SMPP.Common.MessageComposer.IsLastSegment(Of T)(T)
  name.vb: IsLastSegment(Of T)(T)
- uid: Inetlab.SMPP.Common.MessageComposer.GetFullMessage``1(``0)
  commentId: M:Inetlab.SMPP.Common.MessageComposer.GetFullMessage``1(``0)
  id: GetFullMessage``1(``0)
  parent: Inetlab.SMPP.Common.MessageComposer
  langs:
  - csharp
  - vb
  name: GetFullMessage<T>(T)
  nameWithType: MessageComposer.GetFullMessage<T>(T)
  fullName: Inetlab.SMPP.Common.MessageComposer.GetFullMessage<T>(T)
  type: Method
  source:
    remote:
      path: Source/CS/Common/MessageComposer.cs
      branch: master
      repo: C:/Users/Aleksey/Dropbox/Repos/Inetlab.SMPP.git
    id: GetFullMessage
    path: ../Source/CS/Common/MessageComposer.cs
    startLine: 193
  assemblies:
  - Inetlab.SMPP
  namespace: Inetlab.SMPP.Common
  syntax:
    content: 'public string GetFullMessage<T>(T message)where T : ISmppMessage'
    parameters:
    - id: message
      type: '{T}'
    typeParameters:
    - id: T
    return:
      type: System.String
    content.vb: Public Function GetFullMessage(Of T As ISmppMessage)(message As T) As String
  overload: Inetlab.SMPP.Common.MessageComposer.GetFullMessage*
  nameWithType.vb: MessageComposer.GetFullMessage(Of T)(T)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Inetlab.SMPP.Common.MessageComposer.GetFullMessage(Of T)(T)
  name.vb: GetFullMessage(Of T)(T)
references:
- uid: Inetlab.SMPP.Common
  commentId: N:Inetlab.SMPP.Common
  isExternal: false
  name: Inetlab.SMPP.Common
  nameWithType: Inetlab.SMPP.Common
  fullName: Inetlab.SMPP.Common
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Inetlab.SMPP.Common.MessageComposer.Timeout*
  commentId: Overload:Inetlab.SMPP.Common.MessageComposer.Timeout
  isExternal: false
  name: Timeout
  nameWithType: MessageComposer.Timeout
  fullName: Inetlab.SMPP.Common.MessageComposer.Timeout
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Inetlab.SMPP.Common.MessageEventHandler
  commentId: T:Inetlab.SMPP.Common.MessageEventHandler
  parent: Inetlab.SMPP.Common
  isExternal: false
  name: MessageEventHandler
  nameWithType: MessageEventHandler
  fullName: Inetlab.SMPP.Common.MessageEventHandler
- uid: Inetlab.SMPP.Common.MessageComposer.Timeout
  commentId: P:Inetlab.SMPP.Common.MessageComposer.Timeout
- uid: Inetlab.SMPP.Common.MessageComposer.#ctor*
  commentId: Overload:Inetlab.SMPP.Common.MessageComposer.#ctor
  isExternal: false
  name: MessageComposer
  nameWithType: MessageComposer.MessageComposer
  fullName: Inetlab.SMPP.Common.MessageComposer.MessageComposer
- uid: Inetlab.SMPP.Common.MessageComposer.AddMessage*
  commentId: Overload:Inetlab.SMPP.Common.MessageComposer.AddMessage
  isExternal: false
  name: AddMessage
  nameWithType: MessageComposer.AddMessage
  fullName: Inetlab.SMPP.Common.MessageComposer.AddMessage
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  isExternal: false
  name: T
  nameWithType: T
  fullName: T
- uid: Inetlab.SMPP.Common.MessageComposer.IsLastSegment*
  commentId: Overload:Inetlab.SMPP.Common.MessageComposer.IsLastSegment
  isExternal: false
  name: IsLastSegment
  nameWithType: MessageComposer.IsLastSegment
  fullName: Inetlab.SMPP.Common.MessageComposer.IsLastSegment
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Inetlab.SMPP.Common.MessageComposer.GetFullMessage*
  commentId: Overload:Inetlab.SMPP.Common.MessageComposer.GetFullMessage
  isExternal: false
  name: GetFullMessage
  nameWithType: MessageComposer.GetFullMessage
  fullName: Inetlab.SMPP.Common.MessageComposer.GetFullMessage
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
